name: truecash
description: "True Cash: Premium Financial Management"
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.3
  sqlite3_flutter_libs: ^0.5.24
  path: ^1.9.0
  intl: ^0.20.2
  csv: ^6.0.0
  path_provider: ^2.1.3
  fl_chart: ^0.70.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.svg