name: truecash
description: "True Cash: Premium Financial Management"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.3
  sqlite3_flutter_libs: ^0.5.24
  path: ^1.9.0
  intl: ^0.20.2
  csv: ^6.0.0
  path_provider: ^2.1.3
  fl_chart: ^1.1.1
  flutter_svg: ^2.0.10+1
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  shared_preferences: ^2.5.4
  sqflite_common_ffi_web: ^1.1.1
  file_picker: ^10.3.8
  share_plus: ^12.0.1
  web: ^1.1.1
  google_fonts: ^6.1.0
  local_auth: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
  macos:
    generate: true
    image_path: "assets/images/logo.png"
  linux:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.svg
    - assets/images/logo.png